#!name=Apple WLOC Location Spoofer
#!desc=Modify Apple's network-based location coordinates | Picker page: https://idw.jibersodardy.workers.dev
#!author=Yu9191 Rewrite
#!homepage=https://github.com/sodardyjiber/wloc-uf

[rewrite_local]
^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc url script-response-body https://raw.githubusercontent.com/sodardyjiber/wloc-uf/main/dist/wloc.js
^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save url script-echo-response https://raw.githubusercontent.com/sodardyjiber/wloc-uf/main/dist/wloc-settings.js

[mitm]
hostname = gs-loc.apple.com, gs-loc-cn.apple.com
