#!name=Apple WLOC Location Spoofer
#!desc=Modify Apple's network-based location coordinates (Shadowrocket) | Picker page: https://idw.jibersodardy.workers.dev
#!author=Yu9191 Rewrite
#!homepage=https://github.com/sodardyjiber/wloc-uf
#!icon=https://raw.githubusercontent.com/sodardyjiber/wloc-uf/main/wloc.jpg
#!category=Tools

[Script]
Apple WLOC = type=http-response,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/clls\/wloc,requires-body=1,binary-body-mode=1,max-size=0,timeout=30,script-path=https://raw.githubusercontent.com/sodardyjiber/wloc-uf/main/dist/wloc.js,argument=longitude=113.94114&latitude=22.544577&accuracy=25&logLevel=info
WLOC Settings = type=http-request,pattern=^https?:\/\/gs-loc(-cn)?\.apple\.com\/wloc-settings\/save,requires-body=0,max-size=0,timeout=10,script-path=https://raw.githubusercontent.com/sodardyjiber/wloc-uf/main/dist/wloc-settings.js

[MITM]
hostname = %APPEND% gs-loc.apple.com, gs-loc-cn.apple.com
